#!/bin/bash
# usage: e6-brief-mac.sh <agent> <worktree> <lang: mo|go|elixir>   change 6's brief for the sessions resumed on Robert's Mac
# (18 Sep 2026): e6-brief.sh word for word with the Mac's paths, the predecessor's work in progress named, and the
# 4 GB guard stated (the out-of-memory rule). Disclosed on erosion-round.md: a resumed maintainer, not a fresh one.
A=$1; W=$2; L=$3; M=/Users/robertguss/Projects/startups/mo-lang
case $L in
  mo) WHERE="the Mo program in examples/programs/jobq/ (the toolchain binary is toolchain/zig-out/bin/mo; never run zig build or zig build test; read examples/README.md first; the language spec in mo-wiki/spec/design-v0/ in this worktree is current, including chapter 3's Processes list and the stdlib table)";;
  go) WHERE="the Go program in experiments/control-run/go/ (go, staticcheck on PATH)";;
  elixir) WHERE="the Elixir program in experiments/control-run/elixir/jobq/ (Elixir 1.18 on OTP 27 through mise: run 'eval \"\$(mise env)\"' in this worktree first; mix, dialyzer, credo, ExUnit)";;
esac
B="You are a worker on a software project in the worktree $W. Your one task: make the change described in $M/mo-wiki/spec/programs/01g-job-queue-change-6.md (read it there; it is not in your worktree) to $WHERE. Your predecessor's work in progress (the last commits, 'jobq: change 6 (work in progress, the VM session stopped)') and its report REPORT-change-6-wip.md are in the worktree; it worked on a Linux VM and this machine is a Mac (macOS, 14 cores): read the report first, continue from it, and redo on this machine anything it measured there. The existing tests must pass, the new behaviour must have tests, and the service must keep its durability: every change is on the disk before the response that reports it. The spec's speed budget is part of being done: run the bench command it asks for against your change-6 program and against the change-3 program from this worktree's history, both on this machine with nothing else of yours running, and put both runs' lines in the report. Run every server, bench, test, and toolchain process under the guard, which kills it past a timeout or 4 GB of memory: python3 $M/toolchain/bench/step36/guard.py 300 -- <command> (a longer timeout only where a run needs it); never start one without it. Never use tr, cat, or ls in scripts (aliased on this machine; use python3). Keep a count of your loops, carrying on from your predecessor's: every time a check, a build, or a test fails, note the diagnostic or the failing test and whether your next edit fixed it. Commit when green with the subject 'jobq: change 6' and the trailer 'Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>'; do not push. Do not stop early; stop when every check and test is green and the budget is met, with the wall-clock (yours, and the predecessor's beside it), the loop count by cause (and whether the first fix worked), the files changed, the two bench runs, the list of declared errors and the test that reaches each, and a numbered list 'Decisions the spec did not cover', and write that same report to REPORT-change-6.md at the worktree root."
herdr agent prompt "$A" "$B" 2>&1 | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('result',d).get('type', d))"
