import os, hmac, hashlib, json, base64, sys
from cryptography.hazmat.primitives.ciphers.aead import AESGCM, ChaCha20Poly1305
from cryptography.hazmat.primitives.asymmetric import ed25519, x25519
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes
import random
random.seed(int(sys.argv[1]))
rb=lambda n: bytes(random.getrandbits(8) for _ in range(n))
h=lambda b: b.hex()
key, nonce, aad = rb(32), rb(12), rb(random.randint(0,100))
plain = rb(random.randint(1,70000))
big = rb(150_000)
gcm = AESGCM(key).encrypt(nonce, plain, aad)
cc = ChaCha20Poly1305(key).encrypt(nonce, plain, aad)
seed = rb(32); sk = ed25519.Ed25519PrivateKey.from_private_bytes(seed)
pub = sk.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
msg = rb(random.randint(0,3000)); sig = sk.sign(msg)
xa, xb = rb(32), rb(32)
XA=x25519.X25519PrivateKey.from_private_bytes(xa); XB=x25519.X25519PrivateKey.from_private_bytes(xb)
xpub_b = XB.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
shared = XA.exchange(XB.public_key())
ikm, salt, info = rb(50), rb(20), rb(30)
hk = HKDF(algorithm=hashes.SHA256(), length=8160, salt=salt, info=info).derive(ikm)
exp = {
 "sha256_big": hashlib.sha256(big).hexdigest(), "sha512_plain": hashlib.sha512(plain).hexdigest(),
 "hmac": hmac.new(key, plain, hashlib.sha256).hexdigest(), "hkdf_sha": hashlib.sha256(hk).hexdigest(),
 "gcm": h(gcm), "cc": h(cc), "sig": h(sig), "shared": h(shared), "pub": h(pub), "xpub_b": h(xpub_b),
}
mo = f'''# run:
module Probe.Crypto
expose main

intent "Fable's own inputs for step 35, generated by python's cryptography, compared outside."

fn unhex(text: String) : List(UInt8)
  Hash.from_hex(text) or []
end

fn main(platform: Platform)
  out = platform.stdout
  key = unhex("{h(key)}")
  nonce = unhex("{h(nonce)}")
  aad = unhex("{h(aad)}")
  plain = unhex("{h(plain)}")
  big = unhex("{h(big)}")
  out.write_line("sha256_big #{{Hash.hex(Hash.sha256(big))}}")
  out.write_line("sha512_plain #{{Hash.hex(Hash.sha512(plain))}}")
  out.write_line("hmac #{{Hash.hex(Hash.hmac_sha256(key, plain))}}")
  out.write_line("hkdf_sha #{{Hash.hex(Hash.sha256(Hash.hkdf_sha256(unhex("{h(ikm)}"), unhex("{h(salt)}"), unhex("{h(info)}"), 8160)))}}")
  gcm = AesGcm.seal(key, nonce, plain, aad)
  out.write_line("gcm #{{Hash.hex(gcm)}}")
  out.write_line("gcm_open_ok #{{AesGcm.open(key, nonce, gcm, aad) == Some(plain)}}")
  last = gcm.last() or 0
  flipped = gcm.take(gcm.size - 1).push(if last == 255: 0 else: last + 1)
  out.write_line("gcm_open_flipped_tag #{{AesGcm.open(key, nonce, flipped, aad) == None}}")
  out.write_line("gcm_open_short #{{AesGcm.open(key, nonce, gcm.take(15), aad) == None}}")
  out.write_line("gcm_open_wrong_aad #{{AesGcm.open(key, nonce, gcm, aad.push(1)) == None}}")
  out.write_line("gcm_empty #{{AesGcm.seal(key, nonce, [], []).size}}")
  cc = ChaCha.seal(key, nonce, plain, aad)
  out.write_line("cc #{{Hash.hex(cc)}}")
  out.write_line("cc_open_ok #{{ChaCha.open(key, nonce, cc, aad) == Some(plain)}}")
  out.write_line("cc_big_roundtrip #{{ChaCha.open(key, nonce, ChaCha.seal(key, nonce, big, []), []) == Some(big)}}")
  seed = unhex("{h(seed)}")
  msg = unhex("{h(msg)}")
  out.write_line("pub #{{Hash.hex(Ed25519.public(seed))}}")
  sig = Ed25519.sign(seed, msg)
  out.write_line("sig #{{Hash.hex(sig)}}")
  out.write_line("verify_ok #{{Ed25519.verify?(unhex("{h(pub)}"), msg, sig)}}")
  out.write_line("verify_wrong_msg #{{Ed25519.verify?(unhex("{h(pub)}"), msg.push(0), sig)}}")
  out.write_line("verify_bad_key #{{Ed25519.verify?(unhex("ff".repeat(32)), msg, sig)}}")
  out.write_line("xpub_b #{{Hash.hex(X25519.public(unhex("{h(xb)}")))}}")
  out.write_line("shared #{{Hash.hex(X25519.shared(unhex("{h(xa)}"), unhex("{h(xpub_b)}")) or [])}}")
  out.write_line("shared_low_order #{{X25519.shared(unhex("{h(xa)}"), unhex("00".repeat(32))) == None}}")
  out.write_line("from_hex_upper #{{Hash.from_hex("ABCDEF") == Some([171, 205, 239])}}")
  out.write_line("from_hex_odd #{{Hash.from_hex("abc") == None}}")
  out.write_line("from_hex_bad #{{Hash.from_hex("zz") == None}}")
  out.write_line("from_hex_empty #{{Hash.from_hex("") == Some([])}}")
  out.write_line("equal_sizes #{{Hash.equal?([1, 2], [1, 2, 3])}} #{{Hash.equal?(plain, plain)}}")
  phc = Password.hash("pässwörd ☃", unhex("{h(salt[:16])}"))
  out.write_line("phc #{{phc}}")
  out.write_line("phc_verify #{{Password.verify?("pässwörd ☃", phc)}} #{{Password.verify?("pässwörd", phc)}}")
  out.write_line("random_size #{{platform.random.bytes(40).size}}")
end
'''
open(os.path.join(sys.argv[2], "probe.mo"), "w").write(mo)
json.dump(exp, open(os.path.join(sys.argv[2], "expected.json"), "w"))
