//! The error catalog (design-v0/05): every code the toolchain gives, one row each, from
//! the diagnostic tables where the codes are defined: lexer.zig and parser.zig (MO00xx,
//! MO01xx), check.zig (MO02xx, MO03xx), caps.zig (MO04xx), loops.zig and fmt.zig (MO05xx).
//! A row is the code, its category, the template of its `what` (each `<placeholder>`
//! filled in at the finding), its `why`, and what `mo fix` does for it.
//!
//! `zig build errors` writes the rows to mo-wiki/spec/errors.md (errors_gen.zig), and the
//! corpus test fails when that page is not what the tables render.
const std = @import("std");
const Io = std.Io;
const diag = @import("diag.zig");
const lexer = @import("lexer.zig");
const parser = @import("parser.zig");
const check = @import("check.zig");
const caps = @import("caps.zig");
const loops = @import("loops.zig");
const fmt = @import("fmt.zig");

/// The page, from the toolchain directory.
pub const page = "../mo-wiki/spec/errors.md";

/// Every row, in code order.
pub fn rows(gpa: std.mem.Allocator) error{OutOfMemory}![]const diag.Entry {
    var all: std.ArrayList(diag.Entry) = .empty;
    try all.appendSlice(gpa, &lexer.catalog);
    try all.appendSlice(gpa, &parser.catalog);
    for (std.enums.values(check.Code)) |c| try all.append(gpa, check.catalog.get(c));
    for (std.enums.values(caps.Code)) |c| try all.append(gpa, caps.catalog.get(c));
    try all.append(gpa, loops.entry);
    try all.appendSlice(gpa, &fmt.catalog);
    std.mem.sort(diag.Entry, all.items, {}, struct {
        fn lt(_: void, a: diag.Entry, b: diag.Entry) bool {
            return std.mem.lessThan(u8, a.code, b.code);
        }
    }.lt);
    return all.items;
}

pub fn render(w: *Io.Writer, entries: []const diag.Entry) Io.Writer.Error!void {
    try w.writeAll(
        \\# Mo error catalog
        \\
        \\Every diagnostic the Mo toolchain gives, one row per code. A diagnostic is a record with a stable code, a category, a location, `what`, `why`, and zero or more fixes, each with a confidence; there are no warnings (design-v0/05, "Diagnostics teach"). `mo check --json` prints each record as one line of JSON.
        \\
        \\- **what** is the sentence printed at the finding. The row gives its template: each `<placeholder>` is filled in from the code at hand. A code whose findings take more than one shape shows the most common.
        \\- **why** is written once per code, here. It is where Mo's philosophy is taught to a model that has never seen it.
        \\- **mo fix** says what `mo fix` does for the code: it applies every fix of confidence 100 and rewrites the file. `no` means the finding is fixed by hand.
        \\
        \\Generated by `zig build errors` from the diagnostic tables in `toolchain/src/` (`lexer.zig`, `parser.zig`, `check.zig`, `caps.zig`, `loops.zig`, `fmt.zig`). Do not edit this page: the corpus test fails when it differs from the tables.
        \\
        \\| code | category | what | why | mo fix |
        \\|---|---|---|---|---|
        \\
    );
    for (entries) |e| {
        try w.print("| {s} | {t} | `` ", .{ e.code, e.category });
        try cell(w, e.what);
        try w.writeAll(" `` | ");
        try cell(w, e.why);
        try w.writeAll(" | ");
        if (e.fixes.len == 0) try w.writeAll("no");
        for (e.fixes, 0..) |f, i| {
            try w.writeAll(if (i == 0) "yes: " else "; ");
            try cell(w, f);
        }
        try w.writeAll(" |\n");
    }
}

/// Table cell text: a `|` would end the cell.
fn cell(w: *Io.Writer, text: []const u8) Io.Writer.Error!void {
    for (text) |c| {
        if (c == '|') try w.writeByte('\\');
        try w.writeByte(c);
    }
}

/// Whether `what` is `template` with each `<placeholder>` filled in.
pub fn matches(template: []const u8, what: []const u8) bool {
    var rest = what;
    var t = template;
    var first = true;
    while (std.mem.indexOfScalar(u8, t, '<')) |open| {
        const literal = t[0..open];
        if (first) {
            if (!std.mem.startsWith(u8, rest, literal)) return false;
            rest = rest[literal.len..];
        } else {
            const at = std.mem.indexOf(u8, rest, literal) orelse return false;
            rest = rest[at + literal.len ..];
        }
        const close = std.mem.indexOfScalarPos(u8, t, open, '>') orelse return false;
        t = t[close + 1 ..];
        first = false;
    }
    return if (first) std.mem.eql(u8, rest, t) else std.mem.endsWith(u8, rest, t);
}

test "a template matches the sentence it describes, and only that" {
    try std.testing.expect(matches("<name> is bound but never used.", "discount is bound but never used."));
    try std.testing.expect(matches("<a> uses <b> uses <c>; modules have no import cycles.", "A uses B uses A; modules have no import cycles."));
    try std.testing.expect(matches("expected an expression", "expected an expression"));
    try std.testing.expect(!matches("expected an expression", "expected an expression inside #{}"));
    try std.testing.expect(!matches("<name> is bound but never used.", "discount is bound twice."));
}

test "one row per code, each with a what and a why; mo fix handles MO0307, MO0312, and MO0501" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const all = try rows(arena_state.allocator());
    for (all, 0..) |e, i| {
        if (i > 0) try std.testing.expect(std.mem.lessThan(u8, all[i - 1].code, e.code));
        try std.testing.expect(e.what.len > 0 and e.why.len > 0);
        const fixed = std.mem.eql(u8, e.code, "MO0307") or std.mem.eql(u8, e.code, "MO0312") or std.mem.eql(u8, e.code, "MO0501");
        try std.testing.expectEqual(fixed, e.fixes.len > 0);
    }
}

test "every rejects file's expected sentence is its code's what" {
    const gpa = std.testing.allocator;
    const io = std.testing.io;
    var arena_state = std.heap.ArenaAllocator.init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const all = try rows(arena);
    var dir = Io.Dir.cwd().openDir(io, "../examples/rejects", .{ .iterate = true }) catch return;
    defer dir.close(io);
    var it = dir.iterate();
    var checked: u32 = 0;
    while (try it.next(io)) |entry| {
        if (!std.mem.endsWith(u8, entry.name, ".mo")) continue;
        const source = try dir.readFileAlloc(io, entry.name, arena, .limited(1 << 20));
        const at = std.mem.indexOf(u8, source, "\n# expect MO") orelse continue;
        const line = source[at + "\n# expect ".len ..];
        const sentence = line[0..std.mem.indexOfScalar(u8, line, '\n').?];
        const code = sentence[0..6];
        const what = sentence["MO0000: ".len..];
        const row = for (all) |e| {
            if (std.mem.eql(u8, e.code, code)) break e;
        } else return error.TestUnexpectedResult;
        if (!matches(row.what, what)) {
            std.debug.print("{s}: {s} does not match {s}'s what: {s}\n", .{ entry.name, what, code, row.what });
            return error.TestUnexpectedResult;
        }
        checked += 1;
    }
    try std.testing.expect(checked >= 12);
}
